### ISSUE TITLE
Management should view the total orders received and completed.

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#109]
Admin Dashboard Part 1

**Comment by hossain1bd** [comment]
#110 tasks
1. Dash board modification
2. Write DB query 
3. write code to bind DB,SQL with dash board
4. Testing 

#111 tasks
1. Dash board modification
2. Write DB query 
3. write code to bind DB,SQL with dash board
4. Testing

**Comment by evlynmaria** [comment]
@hossain1bd  Should I split the tasks ? The time taken is 2 hrs rt? Please specify the time slot

**Comment by evlynmaria** [comment]
@phidza and @hossain1bd  will be working on this user story . Please complete this , then we can proceed to Admin Dashboard Part 2

**Comment by evlynmaria** [comment]
Completed the part and tested
