### ISSUE TITLE
Data upload Functionality (Order status details)

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#117]

**Comment by evlynmaria** [comment]
#114

**Comment by evlynmaria** [comment]
@imraangithub please update the status

**Comment by imraangithub** [comment]
Hussain ...did you changed the label mistakenly or for any reason?

**Comment by imraangithub** [comment]
Took time to close the task because of the technical problems in system requirements.Done with testing..checked in the code...
