### ISSUE TITLE
Bootstrap Manager and Layout Configuration (UI Styling )

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#119]
Changed to User Story

**Comment by evlynmaria** [comment]
@vanglirajan please update the status

**Comment by vanglirajan** [comment]
Hi Evlyn,

can you create separate task for each page as the total hours of work exceeds two hour.

1.AirwayBill_Clearance.jsp
2. OrderClosing.jsp
3. OrderSearch_Clearance.jsp
4,OrderSubmit.jsp
5.TransportBooking.jsp
6.Update_Clearance.jsp

Thanks,
vangli

**Comment by evlynmaria** [comment]
@vanglirajan Please check the tasks assigned under you.

**Comment by evlynmaria** [comment]
Laid bootstrap and completed the UI styling.
