### ISSUE TITLE
Employee generate Airway Bill Certificate

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#37]

**Comment by evlynmaria** [comment]
@imraangithub Please start working on this user story , estimate the time to complete the task in the comments for each task

**Comment by evlynmaria** [comment]
@imraangithub please give the update for this task?

**Comment by imraangithub** [comment]
working on designing the report. Done with the UI element for running the report.  I need 2 story points for this.

**Comment by evlynmaria** [comment]
@imraangithub  have you checked in the code? It is still missing .

**Comment by imraangithub** [comment]
done with UI element required for running the report and now in testing phase...done also with report design..working on SQL query design and tables and code for report generation...require some more time to complete the task...

**Comment by evlynmaria** [comment]
acceptance test completed
