### ISSUE TITLE
UI element for starting the report(run the report)

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#52]
#37

**Comment by evlynmaria** [comment]
@imraangithub

**Comment by evlynmaria** [comment]
@imraangithub  Could you please send the UI code?

**Comment by imraangithub** [comment]
is in testing phase. Unit testing the functionality.

**Comment by imraangithub** [comment]
done with testing the functionality

**Comment by imraangithub** [comment]
checked in the code..
