### ISSUE TITLE
UI Design for the Transport Booking Form

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#80]
#79

**Comment by evlynmaria** [comment]
@hossain1bd please update the status

**Comment by hossain1bd** [comment]
@evlynmaria , working that, I need script that was used to create invoice table

**Comment by evlynmaria** [comment]
We donot have any invoice table , instead we have the order table with the invoice id , quotation id and order id.
Please fetch the information from the quotation table.

CREATE TABLE `status` (
  `StatusId` int(11) NOT NULL,
  `StatusDesc` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`StatusId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




INSERT INTO `acsms`.`status` (`StatusId`, `StatusDesc`) VALUES ('1', 'Quotation Created');
INSERT INTO `acsms`.`status` (`StatusId`, `StatusDesc`) VALUES ('2', 'Order Created');
INSERT INTO `acsms`.`status` (`StatusId`, `StatusDesc`) VALUES ('3', 'Proforma Invoice Created');
INSERT INTO `acsms`.`status` (`StatusId`, `StatusDesc`) VALUES ('4', 'Customs Clearance Completed');
INSERT INTO `acsms`.`status` (`StatusId`, `StatusDesc`) VALUES ('5', 'AWB Certificate Generated');
INSERT INTO `acsms`.`status` (`StatusId`, `StatusDesc`) VALUES ('6', 'Transport / Carrier Booked');
INSERT INTO `acsms`.`status` (`StatusId`, `StatusDesc`) VALUES ('7', 'Shipment Recieved');
INSERT INTO `acsms`.`status` (`StatusId`, `StatusDesc`) VALUES ('8', 'Order Completed');


CREATE TABLE `order` (
  `transid` int(11) NOT NULL AUTO_INCREMENT,
  `orderid` varchar(45) NOT NULL,
  `quotationid` varchar(45) DEFAULT NULL,
  `invoiceid` varchar(45) DEFAULT NULL,
  `clearanceid` varchar(45) DEFAULT NULL,
  `awbid` varchar(45) DEFAULT NULL,
  `userid` varchar(45) DEFAULT NULL,
  `lasttransdt` date DEFAULT NULL,
  `orderstatus` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`transid`,`orderid`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

**Comment by evlynmaria** [comment]
Sample Data for Order Table 

transid orderid quotationid invoiceid clearanceid awbid userid lasttransdt orderstatus

1 ORD12345 QTN12345 INV12345 CLR12345 AWB12345 USR00001 14/03/2015 1

2 ORD5337 QTN12346 INV5337 CLR5337 AWB5337 USR1234 15/03/2015 2

3 ORD3817 QTN12347 INV3817 CLR3817 AWB3817 USR1234 15/03/2015 3

4 ORD4673 QTN12348 INV4673 CLR4673 AWB4673 USR1234 15/03/2015 5

5 ORD7224 QTN12348 INV7224 CLR7224 AWB7224 USR1234 15/03/2015 6

@hossain1bd

**Comment by hossain1bd** [comment]
@evlynmaria ,
Transport booking form has been completed. Please inform me how to upload through git.

**Comment by hossain1bd** [comment]
@evlynmaria 
Code for transport booking;

TransportBooking.jsp
=====================
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<html>
<head>
<title>Transport Booking</title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>

<form action="TransportBookingBA" method="post">


<table align=center width=100%>
<tr><td>&nbsp; </td></tr>
<tr><td>&nbsp; </td></tr>
<tr><td>&nbsp; </td></tr>
<tr align="center"><h3>Transport Booking</h3></tr>
</table>
<table align=center>
<tr><td>&nbsp; </td></tr>
<tr>
	<td align="left"><h4> Carrier Booking </h1></td> </tr>
<tr>

<tr>
	<td>Invoice ID</td>
	<td> : </td>
	<td><input type=text name=crrName size=15 maxlength=15/></td>
</tr>
<tr>
	<td><p> Carrier Name</p></td>
	<td>:</td> 
	<td><input type=text name=crrName size=15 maxlength=15/> </td>  
</tr>
<tr>
	<td><p> Carrier Booking ID</p></td>
	<td>: </td>	
	<td><input type=text name=crrbookID size=15 maxlength=15/> </td>
</tr>
<tr><td>&nbsp; </td></tr>
<tr>
	<td align="center"><h4> Transport Booking Info</h1></td> </tr>
<tr>
	<td><p> Transport Name<p></td>
    <td>:</td> 
    <td><input type=text name=trnsName size=15 maxlength=15/> </td> 
</tr>
<tr>
  <td><p> Transport Booking ID</p></td>
  <td>:</td> 
  <td><input type=text name=trnsbookID size=15 maxlength=15/></td>
</tr>
<tr><td>&nbsp; </td></tr>
<tr>
	<td align="center"><input type=reset name=reset value="Refresh"/></td>
    <td><input type=submit name=submit value="Submit"/></td>
 </tr>
</table>
</form>

</body>
</html>

TransportBookinDAO
=====================

package com.acsms.org.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;

import com.acsms.org.vo.TransportBookingVO;
import com.mysql.jdbc.Connection;

public class TransportBookingDAO {
	
	private TransportBookingVO objTransportBooking;
	private ConnectionPool connection;
	private Statement statement;
	private Connection connect;
	ConnectionPool customerPool = new ConnectionPool();
	
	public TransportBookingDAO() throws Exception {
		customerPool.setConnect(connect);
		customerPool.setStatement(statement);
		statement = customerPool.getStatement();
	}
	

	// Constructor with values
	public TransportBookingDAO(TransportBookingVO objCustomer) throws Exception {
		super();
		this.objTransportBooking = objCustomer;
		customerPool.setConnect(connect);
		customerPool.setStatement(statement);
		statement = customerPool.getStatement();
	}
	
	// Constructor with no values
	/*
	public CustomerDao() {
		super();
		
	}
	*/
	
	
	// Insert into Database
	public void addNewTransportBooking() throws SQLException{
	
		//String CustID= generateCustomerNo();
	        String insertCustDataSQL = "INSERT INTO Transport_Booking(carr_booking_id,carr_name,"
	        		+ "transport_booking_id,transport_name,invoice_id) VALUES ("
	        		+"\'" + objTransportBooking.getCrrbookID() +"\',"				// Customer ID
	        		+"\'" + objTransportBooking.getCrrName()+"\',"		// Title
	        		+"\'" + objTransportBooking.getTrnsbookID()+"\',"		// Name
	        		+"\'" + objTransportBooking.getTrnsName()+"\',"		// Company
	        		+"\'" + objTransportBooking.getInvoice_id()+"\'"		// Email
	        		+ ");";
	       
	        statement.executeUpdate(insertCustDataSQL);

		}

}

TransportBookingVO
=================
package com.acsms.org.vo;

public class TransportBookingVO {

	// Define the value the same as the CustomerBA
	private String crrName ;
	private String crrbookID;
	private String trnsName ;
	private String trnsbookID ;
	private String invoice_id ;
	
	public TransportBookingVO() {
		super();
		// TODO Auto-generated constructor stub
	}

	// Constructor
	public TransportBookingVO(String crrName,String crrbookID,String trnsName,String trnsbookID,String invoice_id) {
		super();
		this.crrName=crrName ;
		this.crrbookID=crrbookID;
		this.trnsName=trnsName ;
		this.trnsbookID=trnsbookID ;
		this.invoice_id=invoice_id ;
	}
	
	// Setters and getters for all the variables
	
	
	// Title
	
	public String getCrrName() {
		return crrName;
	}

	public void setCrrName(String crrName) {
		this.crrName = crrName;
	}

	public String getCrrbookID() {
		return crrbookID;
	}

	public void setCrrbookID(String crrbookID) {
		this.crrbookID = crrbookID;
	}

	public String getTrnsName() {
		return trnsName;
	}

	public void setTrnsName(String trnsName) {
		this.trnsName = trnsName;
	}

	public String getTrnsbookID() {
		return trnsbookID;
	}

	public void setTrnsbookID(String trnsbookID) {
		this.trnsbookID = trnsbookID;
	}

	public String getInvoice_id() {
		return invoice_id;
	}
	public void setInvoice_id(String invoice_id) {
		this.invoice_id =invoice_id;
	}
		
}

TransportBookingBA
=================
package com.acsms.org.ba;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.acsms.org.dao.CustomerDao;
import com.acsms.org.dao.TransportBookingDAO;
import com.acsms.org.vo.TransportBookingVO;

/**
 * Servlet implementation class TransportBookingBA
 */
@WebServlet("/TransportBookingBA")
public class TransportBookingBA extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public TransportBookingBA() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		String crrName = request.getParameter("crrName");
		String crrbookID = request.getParameter("crrbookID");
		String trnsName = request.getParameter("trnsName");
		String trnsbookID = request.getParameter("trnsbookID");
		String invoice_id = request.getParameter("invoice_id");
			
		TransportBookingVO objTransportBooking = new TransportBookingVO(crrName,crrbookID,trnsName,trnsbookID,invoice_id);		
			
		//String Custid="";
		TransportBookingDAO objTransportBookingDAO = null;
		try {
			objTransportBookingDAO = new TransportBookingDAO(objTransportBooking);
			objTransportBookingDAO.addNewTransportBooking();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}	
}
