### ISSUE TITLE
Employee can close the order after confirming the shipment.

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#85]
@phidza Please give the individual estimate for the tasks for the user story

**Comment by evlynmaria** [comment]
@phidza Could you please update the status of the tasks.

**Comment by phidza** [comment]
I have spent too much tim trying to figure out the code for updation logic of closing order and do need some help thanks

**Comment by evlynmaria** [comment]
Acceptance test completed.
