### ISSUE TITLE
Write and tune the SQL Query database for  the Finalized Quotation

### ISSUE THREAD

**Issue by evlynmaria** [GroupMaria/ACSMS#9]
#1 Hossain

**Comment by evlynmaria** [comment]
Assigned to @hossian

**Comment by hossain1bd** [comment]
Split this task into 4 issues @evlynmaria 
1. Design database for quotation, invoice, customer and tables
2. create scripts to create tables with validation
3. create procedures to insert data to tables
4. create procedure to read data from tables
